// Habilidades e features de classe por nível - D&D 5e

export interface ClassFeature {
  level: number;
  name: string;
  description: string;
  type: "feature" | "ability_score_improvement" | "spellcasting" | "subclass";
}

// Features por classe e nível
export const CLASS_FEATURES: Record<string, ClassFeature[]> = {
  "Bárbaro": [
    { level: 1, name: "Fúria", description: "Você pode entrar em fúria durante o combate", type: "feature" },
    { level: 1, name: "Defesa sem Armadura", description: "CA = 10 + DES + CON quando não está usando armadura", type: "feature" },
    { level: 2, name: "Ataque Imprudente", description: "Você pode fazer um ataque adicional como ação bônus", type: "feature" },
    { level: 2, name: "Sentido do Perigo", description: "Vantagem em testes de Destreza contra efeitos que você pode ver", type: "feature" },
    { level: 3, name: "Caminho Primitivo", description: "Escolha um caminho primitivo", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Ataque Extra", description: "Você pode atacar duas vezes ao usar a ação Ataque", type: "feature" },
    { level: 5, name: "Movimento Rápido", description: "Sua velocidade aumenta em 3m quando não está usando armadura pesada", type: "feature" },
    { level: 7, name: "Instinto Selvagem", description: "Vantagem em testes de iniciativa", type: "feature" },
    { level: 9, name: "Fúria Brutal (1 dado)", description: "Você pode rolar um dado adicional de dano", type: "feature" },
    { level: 11, name: "Fúria Relâmpago", description: "Você pode fazer um ataque adicional quando entra em fúria", type: "feature" },
    { level: 13, name: "Fúria Brutal (2 dados)", description: "Você pode rolar dois dados adicionais de dano", type: "feature" },
    { level: 15, name: "Fúria Persistente", description: "Sua fúria termina apenas se você cair inconsciente ou terminar voluntariamente", type: "feature" },
    { level: 17, name: "Fúria Brutal (3 dados)", description: "Você pode rolar três dados adicionais de dano", type: "feature" },
    { level: 18, name: "Força Indomável", description: "Você pode usar sua Força em vez de Destreza para CA", type: "feature" },
    { level: 20, name: "Campeão Primitivo", description: "Seus bônus de Força e Constituição aumentam em 4 (máximo 24)", type: "feature" },
  ],
  "Bardo": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Inspiração Bárdica", description: "Você pode inspirar aliados com palavras encorajadoras", type: "feature" },
    { level: 2, name: "Versatilidade com Magia", description: "Você pode aprender magias de qualquer classe", type: "feature" },
    { level: 2, name: "Canção de Descanso", description: "Você pode usar música para ajudar aliados a se recuperarem", type: "feature" },
    { level: 3, name: "Colégio Bárdico", description: "Escolha um colégio bárdico", type: "subclass" },
    { level: 3, name: "Perícia", description: "Você adiciona seu bônus de proficiência ao dano de magias", type: "feature" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Inspiração Bárdica (d8)", description: "Sua inspiração bárdica agora usa d8", type: "feature" },
    { level: 5, name: "Canção de Descanso (d8)", description: "Sua canção de descanso agora usa d8", type: "feature" },
    { level: 6, name: "Contramágica", description: "Você pode usar sua reação para interromper magias", type: "feature" },
    { level: 10, name: "Magia Mística", description: "Você aprende duas magias de qualquer classe", type: "feature" },
    { level: 10, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Magia Mística", description: "Você aprende mais duas magias de qualquer classe", type: "feature" },
    { level: 15, name: "Inspiração Bárdica (d10)", description: "Sua inspiração bárdica agora usa d10", type: "feature" },
    { level: 18, name: "Magia Mística", description: "Você aprende mais duas magias de qualquer classe", type: "feature" },
    { level: 20, name: "Inspiração Superior", description: "Quando você rola iniciativa, você recupera um uso de Inspiração Bárdica", type: "feature" },
  ],
  "Bruxo": [
    { level: 1, name: "Magia de Pacto", description: "Você conjura magias através de um pacto", type: "spellcasting" },
    { level: 1, name: "Truques Arcanos", description: "Você aprende dois truques", type: "feature" },
    { level: 2, name: "Invocações Arcanas", description: "Você aprende duas invocações arcanas", type: "feature" },
    { level: 3, name: "Pacto Boon", description: "Escolha um pacto boon", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Invocação Arcana", description: "Você aprende mais uma invocação arcana", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 11, name: "Magia Arcanum (6º nível)", description: "Você aprende uma magia de 6º nível", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 13, name: "Magia Arcanum (7º nível)", description: "Você aprende uma magia de 7º nível", type: "feature" },
    { level: 15, name: "Magia Arcanum (8º nível)", description: "Você aprende uma magia de 8º nível", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 17, name: "Magia Arcanum (9º nível)", description: "Você aprende uma magia de 9º nível", type: "feature" },
    { level: 20, name: "Mestre Arcano", description: "Você recupera todos os seus slots de magia após um descanso curto", type: "feature" },
  ],
  "Clérigo": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Domínio Divino", description: "Escolha um domínio divino", type: "subclass" },
    { level: 2, name: "Canalizar Divindade", description: "Você pode canalizar energia divina", type: "feature" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Destruir Mortos-Vivos", description: "Você pode destruir mortos-vivos com Canalizar Divindade", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Intervenção Divina", description: "Você pode pedir ajuda direta à sua divindade", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Destruir Mortos-Vivos (CR 2)", description: "Você pode destruir mortos-vivos de CR 2 ou menor", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 17, name: "Destruir Mortos-Vivos (CR 3)", description: "Você pode destruir mortos-vivos de CR 3 ou menor", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Intervenção Divina (Garantida)", description: "Sua intervenção divina é garantida uma vez por semana", type: "feature" },
  ],
  "Druida": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Forma Selvagem", description: "Você pode se transformar em animais", type: "feature" },
    { level: 2, name: "Círculo Druídico", description: "Escolha um círculo druídico", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Forma Selvagem (CR 1/4)", description: "Você pode se transformar em animais de CR 1/4", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Forma Selvagem (CR 1)", description: "Você pode se transformar em animais de CR 1", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 18, name: "Forma Selvagem (CR 2)", description: "Você pode se transformar em animais de CR 2", type: "feature" },
    { level: 18, name: "Forma Selvagem (Sem Limite)", description: "Você pode usar Forma Selvagem quantas vezes quiser", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Forma Selvagem (CR 3)", description: "Você pode se transformar em animais de CR 3", type: "feature" },
    { level: 20, name: "Forma Selvagem (Sem Limite)", description: "Você pode usar Forma Selvagem quantas vezes quiser", type: "feature" },
  ],
  "Feiticeiro": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Origem Feiticeira", description: "Escolha uma origem feiticeira", type: "subclass" },
    { level: 2, name: "Magia Fontal", description: "Você pode usar pontos de magia para criar slots de magia", type: "feature" },
    { level: 3, name: "Metamágica", description: "Você aprende duas opções de metamágica", type: "feature" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Magia Fontal (2 pontos)", description: "Você ganha mais pontos de magia", type: "feature" },
    { level: 6, name: "Metamágica", description: "Você aprende mais uma opção de metamágica", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Metamágica", description: "Você aprende mais uma opção de metamágica", type: "feature" },
    { level: 11, name: "Magia Fontal (3 pontos)", description: "Você ganha mais pontos de magia", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 17, name: "Magia Fontal (4 pontos)", description: "Você ganha mais pontos de magia", type: "feature" },
    { level: 17, name: "Metamágica", description: "Você aprende mais uma opção de metamágica", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Magia Restaurada", description: "Você recupera 4 pontos de magia após um descanso curto", type: "feature" },
  ],
  "Guerreiro": [
    { level: 1, name: "Estilo de Combate", description: "Escolha um estilo de combate", type: "feature" },
    { level: 1, name: "Segunda Respiração", description: "Você pode se recuperar com uma ação bônus", type: "feature" },
    { level: 2, name: "Ação Surge", description: "Você pode fazer uma ação adicional", type: "feature" },
    { level: 3, name: "Arquétipo Marcial", description: "Escolha um arquétipo marcial", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Ataque Extra", description: "Você pode atacar duas vezes ao usar a ação Ataque", type: "feature" },
    { level: 6, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 7, name: "Conhecimento Marcial", description: "Você aprende manobras marciais", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 9, name: "Indomável", description: "Você pode repetir testes de resistência", type: "feature" },
    { level: 10, name: "Conhecimento Marcial", description: "Você aprende mais manobras marciais", type: "feature" },
    { level: 11, name: "Ataque Extra (3x)", description: "Você pode atacar três vezes ao usar a ação Ataque", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 13, name: "Indomável (2x)", description: "Você pode repetir testes de resistência duas vezes", type: "feature" },
    { level: 14, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 15, name: "Conhecimento Marcial", description: "Você aprende mais manobras marciais", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 17, name: "Ação Surge (2x)", description: "Você pode usar Ação Surge duas vezes", type: "feature" },
    { level: 17, name: "Indomável (3x)", description: "Você pode repetir testes de resistência três vezes", type: "feature" },
    { level: 18, name: "Conhecimento Marcial", description: "Você aprende mais manobras marciais", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Ataque Extra (4x)", description: "Você pode atacar quatro vezes ao usar a ação Ataque", type: "feature" },
  ],
  "Ladino": [
    { level: 1, name: "Ataque Furtivo", description: "Você pode causar dano extra quando tem vantagem", type: "feature" },
    { level: 1, name: "Perícias de Ladino", description: "Você tem proficiência em perícias de ladino", type: "feature" },
    { level: 2, name: "Ação Astuta", description: "Você pode usar uma ação bônus para se esconder ou se desengajar", type: "feature" },
    { level: 3, name: "Arquétipo Ladino", description: "Escolha um arquétipo ladino", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Esquiva Inesperada", description: "Você pode usar sua reação para reduzir dano pela metade", type: "feature" },
    { level: 6, name: "Perícia", description: "Você adiciona seu bônus de proficiência a perícias específicas", type: "feature" },
    { level: 7, name: "Evasão", description: "Você pode evitar dano de efeitos de área", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 11, name: "Talento Confiável", description: "Você sempre rola pelo menos 10 em testes de perícia", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 13, name: "Ataque Furtivo (7d6)", description: "Seu ataque furtivo causa 7d6 de dano extra", type: "feature" },
    { level: 14, name: "Mente Impenetrável", description: "Você tem vantagem em testes de resistência contra magia", type: "feature" },
    { level: 15, name: "Ataque Furtivo (8d6)", description: "Seu ataque furtivo causa 8d6 de dano extra", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 17, name: "Ataque Furtivo (9d6)", description: "Seu ataque furtivo causa 9d6 de dano extra", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Ataque Furtivo (10d6)", description: "Seu ataque furtivo causa 10d6 de dano extra", type: "feature" },
  ],
  "Mago": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Recuperação Arcana", description: "Você pode recuperar slots de magia após um descanso curto", type: "feature" },
    { level: 2, name: "Tradição Arcana", description: "Escolha uma tradição arcana", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 6, name: "Tradição Arcana", description: "Você ganha uma habilidade da sua tradição arcana", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Tradição Arcana", description: "Você ganha mais uma habilidade da sua tradição arcana", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Tradição Arcana", description: "Você ganha mais uma habilidade da sua tradição arcana", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 18, name: "Magia de Nível Superior", description: "Você pode conjurar uma magia de 1º e 2º nível sem usar slots", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Mestre Arcano", description: "Você recupera dois slots de magia de 3º nível após um descanso curto", type: "feature" },
  ],
  "Monge": [
    { level: 1, name: "Artes Marciais", description: "Você pode usar Destreza para ataques desarmados", type: "feature" },
    { level: 1, name: "Defesa sem Armadura", description: "CA = 10 + DES + SAB quando não está usando armadura", type: "feature" },
    { level: 2, name: "Ki", description: "Você ganha pontos de ki", type: "feature" },
    { level: 2, name: "Movimento sem Armadura", description: "Sua velocidade aumenta quando não está usando armadura", type: "feature" },
    { level: 3, name: "Tradição Monástica", description: "Escolha uma tradição monástica", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 4, name: "Desvio Lento", description: "Você pode reduzir dano de queda", type: "feature" },
    { level: 5, name: "Ataque Extra", description: "Você pode fazer um ataque adicional como ação bônus", type: "feature" },
    { level: 5, name: "Golpe Atordoante", description: "Você pode atordoar inimigos com seus ataques", type: "feature" },
    { level: 6, name: "Golpe com Ki", description: "Seus ataques desarmados contam como mágicos", type: "feature" },
    { level: 7, name: "Evasão", description: "Você pode evitar dano de efeitos de área", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Pureza Corporal", description: "Você é imune a doenças e venenos", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 13, name: "Idioma dos Elementos", description: "Você pode entender e falar todos os idiomas", type: "feature" },
    { level: 14, name: "Diamante Alma", description: "Você tem vantagem em testes de resistência contra magia", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 18, name: "Corpo Vazio", description: "Você pode se tornar invisível e intangível", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Perfeição", description: "Você recupera 4 pontos de ki quando inicia o combate", type: "feature" },
  ],
  "Paladino": [
    { level: 1, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 1, name: "Sentido Divino", description: "Você pode detectar presença de criaturas celestiais, infernais ou não-mortas", type: "feature" },
    { level: 1, name: "Mãos Curativas", description: "Você pode curar ferimentos com um toque", type: "feature" },
    { level: 2, name: "Estilo de Combate", description: "Escolha um estilo de combate", type: "feature" },
    { level: 2, name: "Golpe Divino", description: "Você pode gastar slots de magia para causar dano extra", type: "feature" },
    { level: 3, name: "Juramento Sagrado", description: "Escolha um juramento sagrado", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Ataque Extra", description: "Você pode atacar duas vezes ao usar a ação Ataque", type: "feature" },
    { level: 6, name: "Aura de Proteção", description: "Você e aliados próximos têm bônus em testes de resistência", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Aura de Coragem", description: "Você e aliados próximos são imunes a medo", type: "feature" },
    { level: 11, name: "Golpe Divino Melhorado", description: "Seu golpe divino causa mais dano", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Limpar Toque", description: "Você pode remover efeitos de magia", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 18, name: "Aura de Proteção Melhorada", description: "Sua aura de proteção aumenta de alcance", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Juramento Sagrado", description: "Você ganha uma habilidade final do seu juramento", type: "feature" },
  ],
  "Patrulheiro": [
    { level: 1, name: "Favorito", description: "Escolha um tipo de terreno e criatura favoritos", type: "feature" },
    { level: 2, name: "Conjuração", description: "Você pode conjurar magias", type: "spellcasting" },
    { level: 2, name: "Estilo de Combate", description: "Escolha um estilo de combate", type: "feature" },
    { level: 3, name: "Arquétipo de Patrulheiro", description: "Escolha um arquétipo de patrulheiro", type: "subclass" },
    { level: 4, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 5, name: "Ataque Extra", description: "Você pode atacar duas vezes ao usar a ação Ataque", type: "feature" },
    { level: 6, name: "Favorito Melhorado", description: "Seus favoritos são mais eficazes", type: "feature" },
    { level: 8, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 10, name: "Esconderijo Natural", description: "Você pode se esconder quando está em terreno favorito", type: "feature" },
    { level: 12, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 14, name: "Favorito", description: "Escolha mais um tipo de terreno e criatura favoritos", type: "feature" },
    { level: 16, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 18, name: "Sentidos Selvagens", description: "Você tem vantagem em testes de Percepção", type: "feature" },
    { level: 19, name: "Aumento de Atributo", description: "Aumente um atributo em 2 ou dois atributos em 1", type: "ability_score_improvement" },
    { level: 20, name: "Mestre Caçador", description: "Você causa dano extra contra seus favoritos", type: "feature" },
  ],
};

/**
 * Retorna as features de uma classe até um determinado nível
 */
export function getClassFeatures(className: string, level: number): ClassFeature[] {
  const features = CLASS_FEATURES[className] || [];
  return features.filter(f => f.level <= level);
}

/**
 * Retorna as features ganhas em um nível específico
 */
export function getFeaturesAtLevel(className: string, level: number): ClassFeature[] {
  const features = CLASS_FEATURES[className] || [];
  return features.filter(f => f.level === level);
}

