import { Subclass } from './types';

// ============================================================================
// CLÉRIGO - Domínios (Nível 1)
// ============================================================================

export const clericSubclasses: Subclass[] = [
    {
        name: "Domínio da Vida",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "O Domínio da Vida concentra-se na energia positiva vibrante - uma das forças fundamentais do universo - que sustenta toda a vida.",
        features: [
            { level: 1, name: "Proficiência Adicional", description: "Você ganha proficiência com armaduras pesadas" },
            { level: 1, name: "Discípulo da Vida", description: "Suas magias de cura são mais eficazes" },
            { level: 2, name: "Canalizar Divindade: Preservar Vida", description: "Você pode usar Canalizar Divindade para curar feridos" },
            { level: 6, name: "Curador Abençoado", description: "Magias de cura também curam você" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com energia divina" },
            { level: 17, name: "Cura Suprema", description: "Quando você rolar dados para curar, use o valor máximo" },
        ],
        benefits: [
            { type: 'proficiency', value: 'heavy-armor', level: 1, description: 'Proficiência em armaduras pesadas' },
            { type: 'spell', value: ['bless', 'cure-wounds'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Luz",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "Deuses da luz promovem os ideais do renascimento e renovação, verdade, vigilância e beleza.",
        features: [
            { level: 1, name: "Truque Adicional", description: "Você aprende o truque luz" },
            { level: 1, name: "Labareda Protetora", description: "Você pode interpor luz divina entre você e um atacante" },
            { level: 2, name: "Canalizar Divindade: Radiância do Amanhecer", description: "Você pode usar Canalizar Divindade para emanar luz solar" },
            { level: 6, name: "Labareda Aprimorada", description: "Você pode usar Labareda Protetora quando uma criatura atacar seu aliado" },
            { level: 8, name: "Golpe Potente", description: "Você adiciona seu modificador de Sabedoria ao dano de truques" },
            { level: 17, name: "Corona de Luz", description: "Você pode usar sua ação para ativar uma aura de luz solar" },
        ],
        benefits: [
            { type: 'spell', value: ['burning-hands', 'faerie-fire'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio do Conhecimento",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "Os deuses do conhecimento valorizam o aprendizado e a compreensão acima de tudo.",
        features: [
            { level: 1, name: "Bênçãos do Conhecimento", description: "Você aprende dois idiomas e ganha proficiência em duas perícias" },
            { level: 2, name: "Canalizar Divindade: Conhecimento das Eras", description: "Você pode usar Canalizar Divindade para explorar conhecimento divino" },
            { level: 6, name: "Canalizar Divindade: Ler Pensamentos", description: "Você pode usar Canalizar Divindade para ler a mente de uma criatura" },
            { level: 8, name: "Golpe Potente", description: "Você adiciona seu modificador de Sabedoria ao dano de truques" },
            { level: 17, name: "Visões do Passado", description: "Você pode meditar para receber visões do passado" },
        ],
        benefits: [
            { type: 'language', value: 'choose-2', level: 1, description: 'Escolha 2 idiomas' },
            { type: 'skill', value: 'choose-2', level: 1, description: 'Escolha 2 perícias entre Arcana, History, Nature, Religion' },
            { type: 'spell', value: ['command', 'identify'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Natureza",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "Deuses da natureza são tão variados quanto o mundo natural em si.",
        features: [
            { level: 1, name: "Acólito da Natureza", description: "Você aprende um truque de druida e ganha proficiência em uma perícia" },
            { level: 1, name: "Proficiência Adicional", description: "Você ganha proficiência com armaduras pesadas" },
            { level: 2, name: "Canalizar Divindade: Encantar Animais e Plantas", description: "Você pode usar Canalizar Divindade para encantar animais e plantas" },
            { level: 6, name: "Amortecer Elementos", description: "Você e seus aliados ganham resistência a dano" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com energia divina" },
            { level: 17, name: "Mestre da Natureza", description: "Você ganha a habilidade de comandar animais e plantas" },
        ],
        benefits: [
            { type: 'proficiency', value: 'heavy-armor', level: 1, description: 'Proficiência em armaduras pesadas' },
            { type: 'skill', value: 'choose-1', level: 1, description: 'Escolha 1 perícia entre Animal Handling, Nature, Survival' },
            { type: 'spell', value: ['animal-friendship', 'speak-with-animals'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Tempestade",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "Deuses cujos portfólios incluem o Domínio da Tempestade governam tempestades, mar e céu.",
        features: [
            { level: 1, name: "Proficiências Adicionais", description: "Você ganha proficiência com armas marciais e armaduras pesadas" },
            { level: 1, name: "Ira da Tempestade", description: "Você pode retaliar trovejantemente contra atacantes" },
            { level: 2, name: "Canalizar Divindade: Ira Destrutiva", description: "Você pode usar Canalizar Divindade para causar dano máximo" },
            { level: 6, name: "Golpe Trovejante", description: "Quando você causa dano de trovão ou relâmpago, você pode causar dano extra" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com energia divina" },
            { level: 17, name: "Nascido da Tempestade", description: "Você ganha velocidade de voo" },
        ],
        benefits: [
            { type: 'proficiency', value: ['martial-weapons', 'heavy-armor'], level: 1, description: 'Proficiências em combate' },
            { type: 'spell', value: ['fog-cloud', 'thunderwave'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Trapaça",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "Deuses da trapaça são trapaceiros e instigadores que se destacam como uma constante desafio à ordem aceita.",
        features: [
            { level: 1, name: "Bênção do Trapaceiro", description: "Você ganha proficiência em Stealth, Sleight of Hand e Deception" },
            { level: 2, name: "Canalizar Divindade: Invocar Duplicata", description: "Você pode criar uma duplicata ilusória de si mesmo" },
            { level: 6, name: "Canalizar Divindade: Manto de Sombras", description: "Você pode se tornar invisível" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com veneno" },
            { level: 17, name: "Duplicata Aprimorada", description: "Você pode criar até quatro duplicatas" },
        ],
        benefits: [
            { type: 'skill', value: ['stealth', 'sleight-of-hand', 'deception'], level: 1, description: 'Proficiência em perícias de trapaça' },
            { type: 'spell', value: ['charm-person', 'disguise-self'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Guerra",
        className: "Clérigo",
        level: 1,
        source: "PHB",
        description: "A guerra tem muitas manifestações. Pode fazer heróis de pessoas comuns. Pode ser desesperada e horrível.",
        features: [
            { level: 1, name: "Proficiências Adicionais", description: "Você ganha proficiência com armas marciais e armaduras pesadas" },
            { level: 1, name: "Sacerdote da Guerra", description: "Você pode fazer um ataque com arma como ação bônus" },
            { level: 2, name: "Canalizar Divindade: Golpe Guiado", description: "Você pode usar Canalizar Divindade para acertar um ataque" },
            { level: 6, name: "Canalizar Divindade: Bênção do Deus da Guerra", description: "Você pode usar Canalizar Divindade para dar ataques extras" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com energia divina" },
            { level: 17, name: "Avatar da Batalha", description: "Você ganha resistência a dano de armas não-mágicas" },
        ],
        benefits: [
            { type: 'proficiency', value: ['martial-weapons', 'heavy-armor'], level: 1, description: 'Proficiências em combate' },
            { type: 'spell', value: ['divine-favor', 'shield-of-faith'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Forja",
        className: "Clérigo",
        level: 1,
        source: "XGtE",
        description: "Os deuses da forja são patronos de artesãos que trabalham com metal, desde um humilde ferreiro até um poderoso artífice.",
        features: [
            { level: 1, name: "Proficiências Adicionais", description: "Você ganha proficiência com armaduras pesadas e ferramentas de ferreiro" },
            { level: 1, name: "Bênção da Forja", description: "Você pode infundir magia em uma arma ou armadura" },
            { level: 2, name: "Canalizar Divindade: Fúria Artesã", description: "Você pode criar uma arma mágica temporária" },
            { level: 6, name: "Alma da Forja", description: "Você ganha resistência a dano de fogo e +1 de CA com armadura" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com dano de fogo" },
            { level: 17, name: "Santo da Forja e Fogo", description: "Você ganha imunidade a dano de fogo e resistência a dano não-mágico" },
        ],
        benefits: [
            { type: 'proficiency', value: ['heavy-armor', 'smiths-tools'], level: 1, description: 'Proficiências em combate e ferramentas' },
            { type: 'resistance', value: 'fire', level: 6, description: 'Resistência a dano de fogo' },
            { type: 'spell', value: ['identify', 'searing-smite'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Sepultura",
        className: "Clérigo",
        level: 1,
        source: "XGtE",
        description: "Deuses da sepultura vigiam a linha entre a vida e a morte.",
        features: [
            { level: 1, name: "Círculo da Mortalidade", description: "Suas magias de cura são mais eficazes em criaturas com 0 PV" },
            { level: 1, name: "Olhos da Sepultura", description: "Você pode detectar mortos-vivos" },
            { level: 2, name: "Canalizar Divindade: Caminho para a Sepultura", description: "Você pode amaldiçoar uma criatura para ser vulnerável" },
            { level: 6, name: "Sentinela no Portão da Morte", description: "Você pode cancelar ataques críticos" },
            { level: 8, name: "Golpe Potente", description: "Você adiciona seu modificador de Sabedoria ao dano de truques" },
            { level: 17, name: "Guardião de Almas", description: "Você pode selar a alma de um inimigo morto" },
        ],
        benefits: [
            { type: 'spell', value: ['bane', 'false-life'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Ordem",
        className: "Clérigo",
        level: 1,
        source: "TCoE",
        description: "O Domínio da Ordem representa disciplina, bem como devoção às leis que governam uma sociedade.",
        features: [
            { level: 1, name: "Proficiências Adicionais", description: "Você ganha proficiência com armaduras pesadas e uma perícia" },
            { level: 1, name: "Voz da Autoridade", description: "Quando você conjura uma magia em um aliado, ele pode atacar" },
            { level: 2, name: "Canalizar Divindade: Demanda da Ordem", description: "Você pode usar Canalizar Divindade para encantar criaturas" },
            { level: 6, name: "Personificação da Lei", description: "Você se torna encantadoramente persuasivo" },
            { level: 8, name: "Golpe Divino", description: "Você ganha a habilidade de infundir seus golpes com energia psíquica" },
            { level: 17, name: "Ira da Ordem", description: "Inimigos que atacam seus aliados sofrem dano psíquico" },
        ],
        benefits: [
            { type: 'proficiency', value: 'heavy-armor', level: 1, description: 'Proficiência em armaduras pesadas' },
            { type: 'skill', value: 'choose-1', level: 1, description: 'Escolha 1 perícia entre Intimidation, Persuasion' },
            { type: 'spell', value: ['command', 'heroism'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
    {
        name: "Domínio da Paz",
        className: "Clérigo",
        level: 1,
        source: "TCoE",
        description: "O bálsamo da paz floresce no coração de comunidades saudáveis, entre amigos amorosos e em alianças leais.",
        features: [
            { level: 1, name: "Implemento da Paz", description: "Você ganha proficiência em uma perícia" },
            { level: 1, name: "Vínculo Fortalecedor", description: "Você pode forjar um vínculo entre aliados" },
            { level: 2, name: "Canalizar Divindade: Bálsamo da Paz", description: "Você pode usar Canalizar Divindade para curar múltiplas criaturas" },
            { level: 6, name: "Passo Protetor", description: "Você pode se teletransportar para proteger aliados" },
            { level: 8, name: "Golpe Potente", description: "Você adiciona seu modificador de Sabedoria ao dano de truques" },
            { level: 17, name: "Paz Expansiva", description: "Seus vínculos afetam mais criaturas" },
        ],
        benefits: [
            { type: 'skill', value: 'choose-1', level: 1, description: 'Escolha 1 perícia entre Insight, Performance, Persuasion' },
            { type: 'spell', value: ['heroism', 'sanctuary'], level: 1, description: 'Magias de domínio de 1º nível' },
        ],
    },
];
